### ISSUE TITLE
Simplify attributes and properties of classes

### ISSUE THREAD

**Issue by davidpham87** [MariusWirtz/TM1py#14]
Hello,

Although it is recommanded and often forced to use private, restricted and public properties in type languages, these are often avoided in python. It would greatly increase the readibility (and reduce the size) of the code if one avoided all those underscore "private" variables and their accessor methods.

The reason is the dynamic nature of python objects, as one could set new property on the fly to an existing object if one desired.

**Comment by MariusWirtz** [comment]
Hi,

I see your point here. The lines of code could be reduced by hundreds if we chose a different approach.

But IMO there are a few points in favor of the property methods.
- we would need setter methods anyways in many cases. I think Implementing Setters through decorators is the most elegant way. When coding with TM1py we could simply write
` subset.expression = '[Dim1].Members' `
instead of using a setter method.
- after all its the best practice.

**Comment by davidpham87** [comment]
I agree for the tm1py class, but can you tell me the advantages of having a porperty decorator, an underscored attribute and a getter function in the Server class?

**Comment by MariusWirtz** [comment]
I think we can agree on that. Lets use decorators in TM1py if setter methods are required. otherwise we keep it short and simple
